title: Bhavesh Narsai
author: bnarsai
email: bnarsai90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Experienced IT professional with 5 years of technical consultancy. Possessing a broad range of skills
including software development, project management and technical writing. Always keen to embrace and
learn about new technologies..

# social links
twitter_username: bhaveshnarsai # DO NOT include the @ character, or else the build will fail!
github_username:  bnarsai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
